js:
  trailing-commas: all
  bracket-spacing: false
  finder:
    exclude:
      - "build"
      - "docs"
      - "node_modules"
      - "out"
    name:
      - "*.js"
      - Gruntfile.js
    not-name:
      - "*.min.js"
